### ISSUE TITLE
npm ERR! 404 Not found : @canner/render 

### ISSUE THREAD

**Issue by camel2243** [Canner/coren-example#1]
Hello, I encounter  error while type`yarn`.

Can you help me to solve problem?

Thanks.

```
npm ERR! 404 Not found : @canner/render
npm ERR! 404
npm ERR! 404  '@canner/render' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'coren-example'
```

**Comment by ctxhou** [comment]
Hi @camel2243 
Oops, it's our fault. We already solved this bug.
Please pull the new commit and try it again.
Thanks for your report.

**Comment by wwwy3y3** [comment]
since it's solved. I'll close this issue. thanks for the help @camel2243
